# Generated by Django 4.2.20 on 2025-03-24 01:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='file_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
