# Generated by Django 4.2.20 on 2025-03-31 14:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tickets', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='name',
            new_name='event_name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='file_url',
        ),
        migrations.RemoveField(
            model_name='event',
            name='location',
        ),
        migrations.AddField(
            model_name='event',
            name='banner',
            field=models.FileField(blank=True, null=True, upload_to='event_banners/'),
        ),
        migrations.AlterField(
            model_name='event',
            name='date',
            field=models.DateField(),
        ),
    ]
